name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: _STEP_ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test
