name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Login Docker hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          passwrod: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3.0.0
        id: buildx
      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./Dockerfile
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{secrets.DOCKERHUB_USER_NAME}}/nodejs

      # - name: _STEP_ Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: "npm"
      # - run: npm ci
      # - run: pm2 restart node-backend

      # - run: npm run build --if-present
      # - run: npm test
